### ISSUE TITLE
'npm run start' fails due to relative path in harp

### ISSUE THREAD

**Issue by noffle** [npm/docs#463]
See long-ish dump at the bottom of the issue. I **think** this is happening because of the new module pathing logic on npm3: `docs` depends on `harp@^0.18.0`, which seems to be causing `npm run start` to fail to run. It looks like this is due to a [relative require path](https://github.com/sintaxi/harp/blob/d77ec85d7db7b497597769084c6447c8e51abe5a/lib/middleware.js#L10).

Fortunately this was [fixed](https://github.com/sintaxi/harp/commit/3f2298da2c115c7c6ca17ad2ebfc5415a26c26aa#diff-d7dfcb350720309421bbb465055aafdfL10) as of [0.19.0](https://github.com/sintaxi/harp/commit/0a61866b6ac955a06b8c167d9348f48b4a1bdcc6), which touts npm3 compatibility. The current package.json semver of `^0.18.0` doesn't capture the `0.x` range when the major version is 0.

**EDIT**: I tested upgrading `harp` latest and `docs` runs again without issue. It seems unlikely that it's *just* npm3, since it's been out for ages now and nobody else seems to have problems running this project. Ideas from the npm pros?

error dump:
```
stephen // docs $ node index.js 
module.js:339
    throw err;
    ^

Error: Cannot find module '../node_modules/connect/node_modules/send'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:287:25)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/stephen/Projects/Forks/docs/node_modules/harp/lib/middleware.js:10:12)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/stephen/Projects/Forks/docs/node_modules/harp/lib/index.js:8:19)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/stephen/Projects/Forks/docs/index.js:3:12)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:457:10)
  at startup (node.js:136:18)
  at node.js:972:3
```

**Comment by ashleygwilliams** [comment]
just so i have some clarity here- you are running what version of npm?

**Comment by noffle** [comment]
Definitely!

```
$ node -v
v5.0.0

$ npm -v
3.0.0
```

**Comment by ashleygwilliams** [comment]
+1. i merged. thanks so much for this!

**Comment by ashleygwilliams** [comment]
fixed by #464

**Comment by noffle** [comment]
Awesome! I'm still not clear on how nobody noticed this: people run `docs` all the time, right?
